"""add payment tip

Revision ID: f1e53e552e5b
Revises: 0947ecfb8e27
Create Date: 2026-07-09 16:13:48.744453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e53e552e5b'
down_revision = '0947ecfb8e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip', sa.Float(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('tip')

    # ### end Alembic commands ###
